from datetime import datetime

from requests import Session


def authorization_L2(connect: Session, login: str, password: str, headers: dict):
    """Авторизация в L2"""

    json_data = {
        'username': login,
        'password': password,
        'totp': '',
    }

    response = connect.post('http://192.168.10.161/api/users/auth', headers=headers, json=json_data, verify=False)
    return response.status_code, response.json(), response.cookies


def get_operation_plan(connect: Session, headers: dict):
    """Получить план операций"""

    json_data = {
        'start_date': datetime.now().strftime('%Y-%m-%d'),
        'end_date': datetime.now().strftime('%Y-%m-%d'),
        'doc_operate_pk': -1,
        'doc_anesthetist_pk': -1,
        'department_pk': 181,
    }

    response = connect.post(
        'http://192.168.10.161/api/plans/get-plan-by-params',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()

    return response


def check_operation_protocol(connect: Session, history_number: int, headers: dict):
    """Получает данные из раздела Операции"""
    json_data = {
        'direction': history_number,
        'r_type': 'operation',
        'every': False,
    }

    response = connect.post(
        'http://192.168.10.161/api/stationar/directions-by-key',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()
    return response


def create_protocol(connect: Session, history_number: int, service_id: int, headers: dict):
    """Создаёт протокол"""
    json_data = {
        'service': service_id,  # 5 - протокол операции, 479 - предоперационный эпикриз
        'main_direction': history_number,
    }

    response = connect.post(
        'http://192.168.10.161/api/stationar/make-service',
        headers=headers,
        json=json_data,
        verify=False,
    )
    return response.json()


def get_protocol_info(connect: Session, pk: int, headers: dict):

    json_data = {
        'pk': pk,  # номер протокола
        'force': True,
    }

    response = connect.post(
        'http://192.168.10.161/api/directions/paraclinic_form',
        headers=headers,  # заголовки стационара
        json=json_data,
        verify=False,
    ).json()
    return {
        'pk': response.get('researches')[0].get('pk'),
        'patient': response.get('patient').get('fio'),
        'examination_date': response.get('researches')[0].get('examination_date'),
    }


def save_protocol_data(
        connect: Session,
        pk: int,
        direction_pk: int,
        history_number: int,
        implant: str,
        count_implant: str,
        examination_date: str,
        headers: dict
):
    """Сохраняет данные протокола операции"""

    json_data = {
        'force': True,
        'data': {
            'pk': pk,
            'amd': 'not_need',
            'amd_number': None,
            'direction_pk': direction_pk,  # номер протокола, не истории. При создании
            'research': {
                'pk': 471,
                'title': 'Протокол операции (тр)',
                'version': int(f'{pk}0000'),
                'is_paraclinic': False,
                'is_doc_refferal': False,
                'is_gistology': False,
                'is_microbiology': False,
                'is_treatment': False,
                'is_form': False,
                'is_stom': False,
                'isAux': False,
                'is_case': False,
                'is_expertise': False,
                'is_direction_params': False,
                'is_global_direction_params': False,
                'is_monitoring': False,
                'wide_headers': False,
                'comment': '',
                'groups': [
                    {
                        'pk': 3621,
                        'order': 1,
                        'title': 'Сведения о пациенте:',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 19705,
                                'order': 1,
                                'lines': 1,
                                'title': 'Фамилия, имя, отчество (при наличии)',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '%patient_fio',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19706,
                                'order': 2,
                                'lines': 1,
                                'title': 'Дата рождения',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '%patient_born',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 506,
                        'order': 2,
                        'title': '',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 1863,
                                'order': 2,
                                'lines': 3,
                                'title': 'Дата проведения',
                                'hide': False,
                                'values_to_input': [],
                                'value': datetime.today().strftime('%Y-%m-%d'),
                                'field_type': 1,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1864,
                                'order': 3,
                                'lines': 1,
                                'title': 'Время начала',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '18190',
                                'visibility': '',
                                'required': True,
                                'helper': 'Длительность операции',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19642,
                                'order': 4,
                                'lines': 1,
                                'title': 'Дата окончания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 1,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 2438,
                                'order': 5,
                                'lines': 1,
                                'title': 'Время окончания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 18658,
                                'order': 7,
                                'lines': 1,
                                'title': 'Длительность операции',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 23,
                                'can_edit': False,
                                'default_value': '18219',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 507,
                        'order': 3,
                        'title': '',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 1986,
                                'order': 1,
                                'lines': 2,
                                'title': 'Диагноз до операции',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '6424|1856',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19644,
                                'order': 2,
                                'lines': 1,
                                'title': 'Осложнения основного заболевания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19645,
                                'order': 3,
                                'lines': 1,
                                'title': 'Внешняя причина при травмах, отравлениях',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19646,
                                'order': 4,
                                'lines': 1,
                                'title': 'Сопутствующие заболевания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19647,
                                'order': 5,
                                'lines': 1,
                                'title': 'Дополнительные сведения о заболевании',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19643,
                                'order': 6,
                                'lines': 1,
                                'title': 'Группа крови',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '18197',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1865,
                                'order': 7,
                                'lines': 2,
                                'title': 'Название операции',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1866,
                                'order': 8,
                                'lines': 1,
                                'title': 'Код операции',
                                'hide': False,
                                'values_to_input': [
                                    'A16.03.022.004 Интрамедуллярный стержневой остеосинтез (TEN, включительно кости предплечья)',
                                    'A16.03.026 Закрытое вправление перелома с внутренней фиксацией',
                                    'A16.03.028.002 Остеосинтез ключицы',
                                    'A16.03.021 Удаление внутреннего фиксирующего устройства',
                                    'A16.03.034 Репозиция отломков костей при переломах',
                                    'A16.03.022.002 Остеосинтез титановой пластиной',
                                    'A16.01.004 Хирургическая обработка раны или инфицированной ткани',
                                    'A16.04.018 Вправление вывиха сустава',
                                    'A16.02.009.004 Наложение шва сухожилия',
                                    'A16.03.022.005 Остеосинтез с использованием биодеградируемых материалов',
                                    'A16.03.033.002 Наложение наружных фиксирующих устройств с использованием компрессионно-дистракционного аппарата внешней фиксации',
                                    'A16.03.049 Удаление дистракционного аппарата',
                                    'A16.01.009 Ушивание открытой раны (без кожной пересадки)',
                                    'A16.03.026.001 Артроскопическая фиксация остехондральных переломов коленного сустава с помощью винта (перелом межмыщелкового возвышения)',
                                    'A16.04.019.001 Артроскопическое иссечение медиапателярной, инфрапателярной складки коленного сустава',
                                    'A16.04.045 Рассечение медиопателлярной складки артроскопическое',
                                    'A16.04.024.001 Артроскопическая менискэктомия коленного сустава',
                                    'A16.04.019.002 Артроскопическое иссечение тела Гоффа коленного сустава',
                                    'A16.04.047 Артроскопическая санация сустава',
                                    'A16.04.050 Артроскопический шов мениска',
                                    'A16.04.003.001 Артроскопическое удаление свободного или инородного тела сустава',
                                    'A16.02.009.001 Артроскопический латеролиз надколенника',
                                    'A16.01.010.005 Свободная кожная пластика дерматомным перфорированным лоскутом',
                                    'A16.01.010.002 Пластика раны местными тканями',
                                    'A16.01.010.001 Кожная пластика для закрытия раны с использованием метода дерматензии',
                                    'A16.01.017 Удаление доброкачественных новообразований кожи',
                                    'A16.01.031.001 Устранение рубцовой деформации с замещением дефекта местными тканями',
                                    'A16.02.016 Рассечение кольцевидной связки (болезнь Нотта)',
                                    'A16.02.005.003 Пластика сухожилия кисти',
                                    'A16.02.006.001 Удлинение, укорочение, перемещение мышцы и сухожилия с использованием анкерых фиксаторов (транспозиция большеберцовых мышц)',
                                    'A16.01.023 Иссечение рубцов кожи',
                                    'A16.02.017 Пластика сухожильно-связочного аппарата стопы',
                                    'A16.04.039 Вскрытие и дренирование синовиальной сумки',
                                    'A16.02.005.001 Пластика ахиллова сухожилия',
                                    'A16.02.015 Миотомия',
                                    'A16.02.003 Удаление новообразования сухожилия',
                                    'A16.03.013 Проведение дренажа кости',
                                    'A16.03.024.001 Реконструкция кости. Корригирующая деторсионно-варизирующая остеотомия проксимального конца бедренной кости',
                                    'A16.03.024.003 Реконструкция кости. Остеотомия кости',
                                    'A16.03.024.006 Реконструкция кости. Остеотомия кости с использованием биодеградируемых материалов',
                                    'A16.03.024.007 Реконструкция кости. Коррегирующая остеотомия при деформации стоп',
                                    'A16.03.024.008 Реконструкция кости. Коррегирующая остеотомия бедра',
                                    'A16.03.024.009 Реконструкция кости. Коррегирующая остеотомия голени',
                                    'A16.03.024.016 Реконструкция кости. Остеотомия кости с использованием внутренних фиксаторов и аппаратов внешней фиксации',
                                    'A16.03.025.001 Укорочение кости. Остеотомия кости',
                                    'A16.03.084 Замена спиц или стержней в наружном фиксирующем устройстве',
                                    'A16.03.022.006 Интрамедуллярный блокируемый остеосинтез (БИОС)',
                                    'A16.04.012 Артродез стопы и голеностопного сустава',
                                    'A16.04.013 Артродез других суставов',
                                    'A16.04.017.001 Артропластика тазобедренного сустава (при открытом лечение врожденного вывиха бедра)',
                                    'A16.04.017 Артропластика других суставов',
                                    'A16.03.059 Краевая резекция кости (удаление экзостоза, отшнуровавшегося фрагмента)',
                                    'A16.04.023.001 Экзартикуляция пальца кисти',
                                    'A16.04.023.002 Экзартикуляция пальца стопы',
                                    'A16.03.019 Аутотрансплантация кости (при болезни Пертеса)',
                                    'A11.03.001.001 Трепанбиопсия длинных костей под контролем компьютерной томографии',
                                    'A16.04.015.002 Артроскопическая пластика передней крестообразной связки коленного сустава',
                                    'A16.03.026.001 Артроскопическая фиксация остехондральных переломов коленного сустава с помощью винта',
                                ],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1867,
                                'order': 9,
                                'lines': 1,
                                'title': 'Категория сложности',
                                'hide': False,
                                'values_to_input': [
                                    '- Не выбрано',
                                    '1',
                                    '2',
                                    '3',
                                    '4',
                                ],
                                'value': '- Не выбрано',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1994,
                                'order': 10,
                                'lines': 1,
                                'title': 'Оперативное вмешательство',
                                'hide': False,
                                'values_to_input': [
                                    '- Не выбрано',
                                    'плановое',
                                    'экстренное',
                                ],
                                'value': '- Не выбрано',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 508,
                        'order': 4,
                        'title': 'Операционная бригада.',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 18022,
                                'order': 3,
                                'lines': 1,
                                'title': 'Оперировал',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '%docprofile',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 18021,
                                'order': 4,
                                'lines': 1,
                                'title': 'Код хирурга',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 3,
                                'can_edit': False,
                                'default_value': '("{18022}").includes("Зеленин") ? "467" : ("{18022}").includes("Дегтярев") ? "354" : ("{18022}").includes("Остапенко") ? "064" : ("{18022}").includes("Большаков") ? "313" : ("{18022}").includes("Яковлев") ? "140" : ("{18022}").includes("Решетов") ? "400" : ("{18022}").includes("Колганов") ? "328" : ("{18022}").includes("Докучаев") ? "247" : ("{18022}").includes("Шпагин") ? "208" : ("{18022}").includes("Забинов") ? "478" : ("{18022}").includes("Цыренов") ? "341" : ("{18022}").includes("Преториус") ? "246" : ("{18022}").includes("Ипатьева") ? "471" : ("{18022}").includes("Гуфайзин") ? "052" : ("{18022}").includes("Казанцев") ? "271" : ("{18022}").includes("Негрей") ? "531" : ("{18022}").includes("Ипатьева") ? "271" : "-"',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1869,
                                'order': 5,
                                'lines': 1,
                                'title': 'Ассистенты',
                                'hide': False,
                                'values_to_input': [
                                    'Зеленин И. В.',
                                    'Остапенко В. Г.',
                                    'Казанцев А.В.',
                                    'Большаков Г. А.',
                                    'Яковлев А. Б.',
                                    'Дегтярёв А. А.',
                                ],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '{16984} != "манипуляция"',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1870,
                                'order': 6,
                                'lines': 1,
                                'title': 'Анестезиолог',
                                'hide': False,
                                'values_to_input': [
                                    '- Не выбрано',
                                    'Зарубин А.А.',
                                    'Михайловская Д.А.',
                                    'Азаров Д.Ю.',
                                    'Самиев И.К.',
                                    'Марчук А.В.',
                                    'Латынцева И.В.',
                                    'Стальмахович И.В.',
                                    'Шихеев С.Н.',
                                    'Кутателадзе Т.Е.',
                                    'Кур О.К.',
                                    'Савельева О.О.',
                                    'Сахарова И.В.',
                                    'Аверина И.А.',
                                    'Антонова Е.А.',
                                    'Шарапова Е.С.',
                                    'Сыркин Н.В.',
                                    'Обарчук О.Г.',
                                    'Богданов Т.Д.',
                                    'Ковалева И.А.',
                                    'Сидоренко Н.О.',
                                    ' -',
                                ],
                                'value': '- Не выбрано',
                                'field_type': 10,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 18023,
                                'order': 7,
                                'lines': 1,
                                'title': 'Код анестезиолога',
                                'hide': False,
                                'values_to_input': [],
                                'value': '-',
                                'field_type': 3,
                                'can_edit': False,
                                'default_value': '("{1870}").includes("Зарубин") ? "359" : ("{1870}").includes("Михайловская") ? "329" : ("{1870}").includes("Азаров") ? "248" : ("{1870}").includes("Самиев") ? "283" : ("{1870}").includes("Марчук") ? "215" : ("{1870}").includes("Латынцева") ? "276" : ("{1870}").includes("Стальмахович") ? "207" : ("{1870}").includes("Шихеев") ? "137" : ("{1870}").includes("Кутателадзе") ? "301" : ("{1870}").includes("Кур") ? "077" : ("{1870}").includes("Сахарова") ? "315" : ("{1870}").includes("Аверина") ? "447" : ("{1870}").includes("Антонова") ? "217" : ("{1870}").includes("Сыркин") ? "269" : ("{1870}").includes("Обарчук") ? "321" : ("{1870}").includes("Богданов") ? "079" : ("{1870}").includes("Савельева") ? "343": ("{1870}").includes("Ковалева") ? "046" : ("{1870}").includes("Шарапова") ? "060" : ("{1870}").includes("Сидоренко") ? "508" : "-"',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1871,
                                'order': 9,
                                'lines': 1,
                                'title': 'Анестезист',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '18251',
                                'visibility': '{16984} != "манипуляция"',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1872,
                                'order': 10,
                                'lines': 1,
                                'title': 'Операционная медицинская сестра',
                                'hide': False,
                                'values_to_input': [
                                    'Осипова А.К.',
                                    'Баданина Е.А.',
                                    'Корицкая П.Б.',
                                ],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '{16984} != "манипуляция"',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 3804,
                        'order': 5,
                        'title': '',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 20694,
                                'order': 1,
                                'lines': 1,
                                'title': 'Премедикация',
                                'hide': False,
                                'values_to_input': [],
                                'value': 'не проводилась',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': 'не проводилась',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 20695,
                                'order': 2,
                                'lines': 1,
                                'title': 'Степень риска оперативного вмешательства (операции)',
                                'hide': False,
                                'values_to_input': [
                                    'незначительная',
                                    'умеренная',
                                    'высокая',
                                ],
                                'value': 'незначительная',
                                'field_type': 12,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 20696,
                                'order': 3,
                                'lines': 1,
                                'title': 'План оперативного вмешательства (операции)',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '19455',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 509,
                        'order': 6,
                        'title': 'Ход операции',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 1873,
                                'order': 1,
                                'lines': 6,
                                'title': '',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1998,
                                'order': 23,
                                'lines': 1,
                                'title': 'Метод обезболивания',
                                'hide': False,
                                'values_to_input': [
                                    'ТВА ',
                                    'АМН ',
                                    'ЭТН ',
                                    'РА ',
                                ],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '18200',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1875,
                                'order': 25,
                                'lines': 1,
                                'title': 'Макропрепарат',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '{16984} != "манипуляция"',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 2431,
                                'order': 26,
                                'lines': 1,
                                'title': 'Осложнения',
                                'hide': False,
                                'values_to_input': [],
                                'value': 'нет',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': 'нет',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 3640,
                        'order': 7,
                        'title': '',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 19812,
                                'order': 1,
                                'lines': 1,
                                'title': 'Использование медицинских изделий',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19813,
                                'order': 2,
                                'lines': 1,
                                'title': 'Подсчет операционного материала: инструменты',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19814,
                                'order': 3,
                                'lines': 1,
                                'title': 'Подсчет операционного материала: салфетки',
                                'hide': False,
                                'values_to_input': [],
                                'value': '10',
                                'field_type': 18,
                                'can_edit': False,
                                'default_value': '10',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19815,
                                'order': 4,
                                'lines': 1,
                                'title': 'Кровопотеря',
                                'hide': False,
                                'values_to_input': [],
                                'value': '50',
                                'field_type': 18,
                                'can_edit': False,
                                'default_value': '50',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 24896,
                                'order': 6,
                                'lines': 3,
                                'title': 'Имплантированные медицинские изделия',
                                'hide': False,
                                'values_to_input': [],
                                'value': implant,
                                'field_type': 3,
                                'can_edit': True,
                                'default_value': '("{1873}").includes("спиц") ? "спица с перьевидной заточкой без упорной площадки (5430723), в сопроводительной документации нет данных о совместимости с МРТ исследованиями" : ("{1873}").includes("TEN") ? "\'эластичный титановый стержень (10831124), в сопроводительной документации нет данных о совместимости с МРТ исследованиями" : ("{1873}").includes("винт") ? "винт канюлированный (7210724), в сопроводительной документации нет данных о совместимости с МРТ исследованиями" : ("{1873}").includes("стерж") ? "стержень для внутренней фиксации (8760924), в сопроводительной документации нет данных о совместимости с МРТ исследованиями" : ("{1873}").includes("пластин") ? "пластина накостная, в сопроводительной документации нет данных о совместимости с МРТ исследованиями" : "-"',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19816,
                                'order': 6,
                                'lines': 1,
                                'title': 'Количество имплантированных медицинских изделий',
                                'hide': False,
                                'values_to_input': [],
                                'value': count_implant,
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '{24896} != "-"',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 3639,
                        'order': 8,
                        'title': 'Диагноз после оперативного вмешательства (операции):',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 19807,
                                'order': 1,
                                'lines': 1,
                                'title': 'Основное заболевание',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': True,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19808,
                                'order': 2,
                                'lines': 1,
                                'title': 'Осложнения основного заболевания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19809,
                                'order': 3,
                                'lines': 1,
                                'title': 'Внешняя причина при травмах, отравлениях',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19810,
                                'order': 4,
                                'lines': 1,
                                'title': 'Сопутствующие заболевания',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 19811,
                                'order': 5,
                                'lines': 1,
                                'title': 'Дополнительные сведения о заболевании',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                    {
                        'pk': 510,
                        'order': 9,
                        'title': 'Назначения',
                        'show_title': True,
                        'hide': False,
                        'display_hidden': False,
                        'fields': [
                            {
                                'pk': 1876,
                                'order': 1,
                                'lines': 3,
                                'title': '',
                                'hide': False,
                                'values_to_input': [
                                    'Ежедневные перевязки;',
                                    'Нурофен мл per os при болях;',
                                    'Рентген-контроль;',
                                    'Цефтриаксон мг в/в на 10 мл NaCl №5',
                                ],
                                'value': '',
                                'field_type': 0,
                                'can_edit': False,
                                'default_value': '',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                            {
                                'pk': 1877,
                                'order': 2,
                                'lines': 1,
                                'title': 'Переведен в',
                                'hide': False,
                                'values_to_input': [],
                                'value': '',
                                'field_type': 14,
                                'can_edit': False,
                                'default_value': '13519',
                                'visibility': '',
                                'required': False,
                                'helper': '',
                                'controlParam': '',
                                'not_edit': False,
                                'operator_enter_param': False,
                                'deniedGroup': '',
                                'isDiagTable': False,
                            },
                        ],
                        'visibility': '',
                        'fieldsInline': False,
                    },
                ],
                'can_transfer': False,
                'is_extract': False,
                'transfer_direction': None,
                'r_type': 'operation',
                'show_more_services': True,
                'enabled_add_files': True,
                'is_need_send_egisz': False,
            },
            'pacs': None,
            'examination_date': examination_date,
            'templates': [
                {
                    'pk': 717,
                    'title': 'McKay с двух сторон',
                },
                {
                    'pk': 715,
                    'title': 'McKay слева',
                },
                {
                    'pk': 712,
                    'title': 'McKay справа',
                },
                {
                    'pk': 839,
                    'title': 'артро гемартроз слева',
                },
                {
                    'pk': 838,
                    'title': 'артро гемартроз справа',
                },
                {
                    'pk': 835,
                    'title': 'артро Гоффа слева',
                },
                {
                    'pk': 812,
                    'title': 'артро Гоффа справа',
                },
                {
                    'pk': 843,
                    'title': 'артро дискоид латеральный слева',
                },
                {
                    'pk': 842,
                    'title': 'артро дискоид латеральный справа',
                },
                {
                    'pk': 841,
                    'title': 'артро дискоид медиальный слева',
                },
                {
                    'pk': 840,
                    'title': 'артро дискоид медиальный справа',
                },
                {
                    'pk': 864,
                    'title': 'артро задний рог латеральный слева',
                },
                {
                    'pk': 856,
                    'title': 'артро задний рог латеральный справа',
                },
                {
                    'pk': 860,
                    'title': 'артро задний рог медиальный слева',
                },
                {
                    'pk': 852,
                    'title': 'артро задний рог медиальный справа',
                },
                {
                    'pk': 805,
                    'title': 'артро медиапателлярная слева',
                },
                {
                    'pk': 804,
                    'title': 'артро медиапателлярная справа',
                },
                {
                    'pk': 803,
                    'title': 'артро общая',
                },
                {
                    'pk': 865,
                    'title': 'артро передний рог латеральный слева',
                },
                {
                    'pk': 857,
                    'title': 'артро передний рог латеральный справа',
                },
                {
                    'pk': 861,
                    'title': 'артро передний рог медиальный слева',
                },
                {
                    'pk': 853,
                    'title': 'артро передний рог медиальный справа',
                },
                {
                    'pk': 811,
                    'title': 'артро ПКС (полное) слева',
                },
                {
                    'pk': 810,
                    'title': 'артро ПКС (полное) справа',
                },
                {
                    'pk': 809,
                    'title': 'артро ПКС (частично) слева',
                },
                {
                    'pk': 808,
                    'title': 'артро ПКС (частично) справа',
                },
                {
                    'pk': 867,
                    'title': 'артро ручка лейки латеральный слева',
                },
                {
                    'pk': 859,
                    'title': 'артро ручка лейки латеральный справа',
                },
                {
                    'pk': 863,
                    'title': 'артро ручка лейки медиальный слева',
                },
                {
                    'pk': 855,
                    'title': 'артро ручка лейки медиальный справа',
                },
                {
                    'pk': 807,
                    'title': 'артро синовит слева',
                },
                {
                    'pk': 806,
                    'title': 'артро синовит справа',
                },
                {
                    'pk': 866,
                    'title': 'артро тело латеральный слева',
                },
                {
                    'pk': 858,
                    'title': 'артро тело латеральный справа',
                },
                {
                    'pk': 862,
                    'title': 'артро тело медиальный слева',
                },
                {
                    'pk': 854,
                    'title': 'артро тело медиальный справа',
                },
                {
                    'pk': 837,
                    'title': 'артро хондромаляция слева',
                },
                {
                    'pk': 836,
                    'title': 'артро хондромаляция справа',
                },
                {
                    'pk': 711,
                    'title': 'Ахиллотомия по Байеру слева.',
                },
                {
                    'pk': 710,
                    'title': 'Ахиллотомия по Байеру справа',
                },
                {
                    'pk': 714,
                    'title': 'Ахиллотомия с двух сторон',
                },
                {
                    'pk': 583,
                    'title': 'бедро с/3 слева',
                },
                {
                    'pk': 582,
                    'title': 'бедро с/3 справа',
                },
                {
                    'pk': 707,
                    'title': 'Болезнь Нотта слева',
                },
                {
                    'pk': 706,
                    'title': 'Болезнь Нотта справа',
                },
                {
                    'pk': 589,
                    'title': 'большеберцовая кость в/3 слева',
                },
                {
                    'pk': 588,
                    'title': 'большеберцовая кость в/3 справа',
                },
                {
                    'pk': 597,
                    'title': 'большеберцовая кость н/3 слева(TEN)',
                },
                {
                    'pk': 603,
                    'title': 'большеберцовая кость н/3 слева(винт)',
                },
                {
                    'pk': 594,
                    'title': 'большеберцовая кость н/3 справа(TEN)',
                },
                {
                    'pk': 602,
                    'title': 'большеберцовая кость н/3 справа(винт)',
                },
                {
                    'pk': 591,
                    'title': 'большеберцовая кость с/3 слева',
                },
                {
                    'pk': 590,
                    'title': 'большеберцовая кость с/3 справа',
                },
                {
                    'pk': 501,
                    'title': 'внутренний надмыщелок слева',
                },
                {
                    'pk': 498,
                    'title': 'внутренний надмыщелок справа',
                },
                {
                    'pk': 2404,
                    'title': 'вправление предплечья слева',
                },
                {
                    'pk': 2403,
                    'title': 'вправление предплечья справа',
                },
                {
                    'pk': 2236,
                    'title': 'вывих левого бедра по Солтеру',
                },
                {
                    'pk': 2237,
                    'title': 'вывих правого бедра по Солтеру',
                },
                {
                    'pk': 2412,
                    'title': 'вытяжение левая голень',
                },
                {
                    'pk': 2410,
                    'title': 'вытяжение левое бедро',
                },
                {
                    'pk': 2408,
                    'title': 'вытяжение левое плечо',
                },
                {
                    'pk': 2411,
                    'title': 'вытяжение правая голень',
                },
                {
                    'pk': 2409,
                    'title': 'вытяжение правое бедро',
                },
                {
                    'pk': 2407,
                    'title': 'вытяжение правое плечо',
                },
                {
                    'pk': 593,
                    'title': 'голень с/3 слева',
                },
                {
                    'pk': 592,
                    'title': 'голень с/3 справа ',
                },
                {
                    'pk': 509,
                    'title': 'головчатое возвышения слева',
                },
                {
                    'pk': 508,
                    'title': 'головчатое возвышения справа',
                },
                {
                    'pk': 2251,
                    'title': 'двухсторонний вывих бедер',
                },
                {
                    'pk': 2704,
                    'title': 'Динамизация стержня (бедро)',
                },
                {
                    'pk': 2705,
                    'title': 'Динамизация стержня (голень)',
                },
                {
                    'pk': 705,
                    'title': 'Киста Бейкера слева',
                },
                {
                    'pk': 704,
                    'title': 'киста Бейкера справа',
                },
                {
                    'pk': 475,
                    'title': 'ключица слева',
                },
                {
                    'pk': 474,
                    'title': 'ключица справа',
                },
                {
                    'pk': 529,
                    'title': 'локоть с/3 слева',
                },
                {
                    'pk': 527,
                    'title': 'локоть с/3 справа',
                },
                {
                    'pk': 539,
                    'title': 'луч н/3 слева',
                },
                {
                    'pk': 538,
                    'title': 'луч н/3 справа',
                },
                {
                    'pk': 523,
                    'title': 'луч с/3 слева',
                },
                {
                    'pk': 522,
                    'title': 'луч с/3 справа',
                },
                {
                    'pk': 2710,
                    'title': 'межмыщелковое слева',
                },
                {
                    'pk': 2709,
                    'title': 'межмыщелковое справа',
                },
                {
                    'pk': 549,
                    'title': 'палец кисти слева',
                },
                {
                    'pk': 548,
                    'title': 'палец кисти справа',
                },
                {
                    'pk': 544,
                    'title': 'первая пястная слева',
                },
                {
                    'pk': 542,
                    'title': 'первая пястная справа',
                },
                {
                    'pk': 505,
                    'title': 'перелом наружной части мыщелка слева',
                },
                {
                    'pk': 504,
                    'title': 'перелом наружной части мыщелка справа',
                },
                {
                    'pk': 477,
                    'title': 'перелом плеча слева в/3',
                },
                {
                    'pk': 480,
                    'title': 'перелом плеча слева с/3',
                },
                {
                    'pk': 476,
                    'title': 'перелом плеча справа в/3',
                },
                {
                    'pk': 479,
                    'title': 'перелом плеча справа с/3',
                },
                {
                    'pk': 701,
                    'title': 'Пертеса слева',
                },
                {
                    'pk': 700,
                    'title': 'Пертеса справа',
                },
                {
                    'pk': 2766,
                    'title': 'Плоско-вальгусная стопа слева',
                },
                {
                    'pk': 2767,
                    'title': 'Плоско-вальгусная стопа справа',
                },
                {
                    'pk': 605,
                    'title': 'плюсневые кости слева',
                },
                {
                    'pk': 604,
                    'title': 'плюсневые кости справа',
                },
                {
                    'pk': 246,
                    'title': 'По умолчанию',
                },
                {
                    'pk': 535,
                    'title': 'предплечье н/3 слева',
                },
                {
                    'pk': 534,
                    'title': 'предплечье н/3 справа',
                },
                {
                    'pk': 517,
                    'title': 'предплечье с/3 обе кости слева',
                },
                {
                    'pk': 516,
                    'title': 'предплечье с/3 обе кости справа',
                },
                {
                    'pk': 547,
                    'title': 'пястная кость слева',
                },
                {
                    'pk': 546,
                    'title': 'пястная кость справа',
                },
                {
                    'pk': 2402,
                    'title': 'репозиция предплечья слева',
                },
                {
                    'pk': 2401,
                    'title': 'репозиция предплечья справа',
                },
                {
                    'pk': 2406,
                    'title': 'репозиция ч\\мыщелковый слева',
                },
                {
                    'pk': 2405,
                    'title': 'репозиция ч\\мыщелковый справа',
                },
                {
                    'pk': 2739,
                    'title': 'Транспозиция длинного сгибателя пальцев стопы на ладьевидную кость, удлинение Ахиллового сухожилия. Артрориз подтаранного сустава.',
                },
                {
                    'pk': 716,
                    'title': 'Транспозиция передней большеберцовой слева',
                },
                {
                    'pk': 718,
                    'title': 'Транспозиция передней большеберцовой с обеих сторон',
                },
                {
                    'pk': 713,
                    'title': 'Транспозиция передней большеберцовой справа',
                },
                {
                    'pk': 2274,
                    'title': 'Трохлеопластика, Elmslie-Trillat слева',
                },
                {
                    'pk': 2273,
                    'title': 'Трохлеопластика, Elmslie-Trillat справа',
                },
                {
                    'pk': 655,
                    'title': 'удаление бедро с/3 слева(TEN)',
                },
                {
                    'pk': 654,
                    'title': 'удаление бедро с/3 справа(TEN)',
                },
                {
                    'pk': 667,
                    'title': 'удаление голень винт слева',
                },
                {
                    'pk': 666,
                    'title': 'удаление голень винт справа',
                },
                {
                    'pk': 661,
                    'title': 'удаление голень с/3 слева',
                },
                {
                    'pk': 658,
                    'title': 'удаление голень с/3 справа',
                },
                {
                    'pk': 609,
                    'title': 'удаление ключица слева',
                },
                {
                    'pk': 608,
                    'title': 'удаление ключица справа',
                },
                {
                    'pk': 621,
                    'title': 'удаление локоть слева',
                },
                {
                    'pk': 620,
                    'title': 'удаление локоть справа',
                },
                {
                    'pk': 617,
                    'title': 'удаление луч слева',
                },
                {
                    'pk': 616,
                    'title': 'удаление луч справа',
                },
                {
                    'pk': 627,
                    'title': 'удаление обе кости предплечья слева',
                },
                {
                    'pk': 626,
                    'title': 'удаление обе кости предплечья справа',
                },
                {
                    'pk': 615,
                    'title': 'удаление плечо слева TEN',
                },
                {
                    'pk': 611,
                    'title': 'удаление плечо справа TEN',
                },
                {
                    'pk': 653,
                    'title': 'удаление шейка бедра слева',
                },
                {
                    'pk': 652,
                    'title': 'удаление шейка бедра справа',
                },
                {
                    'pk': 490,
                    'title': 'ч/м разгибательный слева',
                },
                {
                    'pk': 489,
                    'title': 'ч/м разгибательный справа',
                },
                {
                    'pk': 494,
                    'title': 'ч/м сгибательный слева',
                },
                {
                    'pk': 492,
                    'title': 'ч/м сгибательный справа',
                },
                {
                    'pk': 573,
                    'title': 'шейка бедра слева винты',
                },
                {
                    'pk': 569,
                    'title': 'шейка бедра справа винты',
                },
                {
                    'pk': 513,
                    'title': 'шейка луча слева',
                },
                {
                    'pk': 512,
                    'title': 'шейка луча справа',
                },
                {
                    'pk': 699,
                    'title': 'Шляттер слева (перфорации)',
                },
                {
                    'pk': 697,
                    'title': 'Шляттер слева (удаление)',
                },
                {
                    'pk': 698,
                    'title': 'Шляттер справа (перфорации)',
                },
                {
                    'pk': 696,
                    'title': 'Шляттер справа (удаление)',
                },
                {
                    'pk': 720,
                    'title': 'Экзостоз бедра слева',
                },
                {
                    'pk': 719,
                    'title': 'Экзостоз бедра справа',
                },
                {
                    'pk': 722,
                    'title': 'Экзостоз голени слева',
                },
                {
                    'pk': 721,
                    'title': 'Экзостоз голень справа',
                },
                {
                    'pk': 709,
                    'title': 'Экзостоз плечо слева',
                },
                {
                    'pk': 708,
                    'title': 'Экзостоз плечо справа',
                },
                {
                    'pk': 703,
                    'title': 'Юношеский эпифизелолиз слева',
                },
                {
                    'pk': 702,
                    'title': 'Юнощеский эпифизеолиз справа',
                },
            ],
            'saved': True,
            'confirmed': False,
            'confirmed_at': None,
            'allow_reset_confirm': False,
            'more': [],
            'sub_directions': [],
            'recipe': [],
            'lab_comment': '',
            'forbidden_edit': False,
            'maybe_onco': False,
            'work_by': None,
            'tube': None,
            'procedure_list': [],
            'is_form': False,
            'children_directions': [],
            'parentDirection': {
                'pk': history_number,
                'service': 'Травматология',
                'is_hospital': True,
            },
            'whoSaved': None,
            'whoConfirmed': None,
            'whoExecuted': None,
            'countFiles': 0,
            'direction': {
                'pk': direction_pk,
            },
            'stationar_research': -1,
        },
        'with_confirm': False,
        'visibility_state': {
            'groups': {
                '506': True,
                '507': True,
                '508': True,
                '509': True,
                '510': True,
                '3621': True,
                '3639': True,
                '3640': True,
                '3804': True,
            },
            'fields': {
                '1863': True,
                '1864': True,
                '1865': True,
                '1866': True,
                '1867': True,
                '1869': True,
                '1870': True,
                '1871': True,
                '1872': True,
                '1873': True,
                '1875': True,
                '1876': True,
                '1877': True,
                '1986': True,
                '1994': True,
                '1998': True,
                '2431': True,
                '2438': True,
                '18021': True,
                '18022': True,
                '18023': True,
                '18658': True,
                '19642': True,
                '19643': True,
                '19644': True,
                '19645': True,
                '19646': True,
                '19647': True,
                '19705': True,
                '19706': True,
                '19807': True,
                '19808': True,
                '19809': True,
                '19810': True,
                '19811': True,
                '19812': True,
                '19813': True,
                '19814': True,
                '19815': True,
                '20694': True,
                '20695': True,
                '20696': True,
                '24896': True,
                '24897': False,
            },
        },
    }

    response = connect.post(
        'http://192.168.10.161/api/directions/paraclinic_result',
        headers=headers,
        json=json_data,
        verify=False,
    ).json()
    return response
